[package]
name = "tasm-lang"
version = "0.1.0"
edition = "2021"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy", "run-cargo-fmt"]

[dependencies]
tasm-lib = { git = "https://github.com/TritonVM/tasm-lib" }
twenty-first = "0.14"
triton-opcodes = { version = "0.14", git = "https://github.com/TritonVM/triton-vm.git", branch = "master" }
triton-vm = { version = "0.14"}
itertools = "0.10"
num = "0.4"
quote = "1.0"
rand = "*"
syn = { version = "1.0", features = ["full", "extra-traits"] }
anyhow = "*"
