[package]
name = "tasm-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tasm-lib = { git = "https://github.com/TritonVM/tasm-lib", branch = "type-annotate-all-snippets" }
twenty-first = "0.14"
triton-opcodes = { version = "0.14", git = "https://github.com/TritonVM/triton-vm.git", branch = "master" }
itertools = "0.10"
num = "0.4"
quote = "1.0"
rand = "*"
syn = { version = "1.0", features = ["full", "extra-traits"] }
anyhow = "*"
