[package]
name = "tasm-lang"
version = "0.18.0"
edition = "2021"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy", "run-cargo-fmt"]

[dependencies]
tasm-lib = { git = "https://github.com/TritonVM/tasm-lib" }
twenty-first = "0.18.0"
triton-opcodes = "0.18.0"
triton-vm = "0.18.0"
itertools = "0.10"
num = "0.4"
quote = "1.0"
rand = "0.8.5"
syn = { version = "1.0", features = ["full", "extra-traits"] }
anyhow = "1.0"
