[package]
name = "tasm-lang"
version = "0.19.0"
edition = "2021"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy", "run-cargo-fmt"]

[dependencies]
anyhow = "1"
tasm-lib = { git = "https://github.com/TritonVM/tasm-lib" }
itertools = "0.10"
num = "0.4"
rand = "0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
triton-opcodes = "0.20.0"
triton-vm = "0.20.0"
twenty-first = "0.19.3"
