[package]
name = "tasm-lang"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = "^0.4.31"
inflections = "1.1"
itertools = "0.11"
num = "0.4"
rand = "0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
tasm-lib = { git = "https://github.com/TritonVM/tasm-lib.git" }
triton-vm = "0.35"
twenty-first = "0.34"

[dev-dependencies]
anyhow = "1"
field_count = "0.1.1"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = [
    "precommit-hook",
    "run-cargo-test",
    "run-cargo-clippy",
    "run-cargo-fmt",
]
