verify_stark_proof_inner_padded_height_256_0_input_words:
| Subroutine                                                                                                              |            Processor |              OpStack |                  Ram |                 Hash |                  U32 |
|:------------------------------------------------------------------------------------------------------------------------|---------------------:|---------------------:|---------------------:|---------------------:|---------------------:|
| verify_stark_proof                                                                                                      |      292231 (100.0%) |      275146 (100.0%) |      299007 (100.0%) |       80443 ( 54.8%) |       76360 (100.0%) |
| ··tasmlib_io_read_stdin___digest                                                                                        |           2 (  0.0%) |           5 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ··tasmlib_io_read_stdin___u32                                                                                           |           4 (  0.0%) |           2 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ··tasmlib_list_new                                                                                                      |          56 (  0.0%) |          44 (  0.0%) |           6 (  0.0%) |           0 (  0.0%) |          64 (  0.1%) |
| ····tasmlib_memory_dyn_malloc                                                                                           |         104 (  0.0%) |          97 (  0.0%) |          10 (  0.0%) |           0 (  0.0%) |         160 (  0.2%) |
| ······tasmlib_memory_dyn_malloc_initialize                                                                              |           3 (  0.0%) |           2 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ··_binop_Lt__LboolR_bool_18_while_loop                                                                                  |           8 (  0.0%) |           6 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           1 (  0.0%) |
| ··_binop_Lt__LboolR_bool_29_while_loop                                                                                  |           8 (  0.0%) |           6 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ··proof_version                                                                                                         |           2 (  0.0%) |           1 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ··box_new_Claim                                                                                                         |         184 (  0.1%) |         143 (  0.1%) |          22 (  0.0%) |           0 (  0.0%) |          66 (  0.1%) |
| ····store_Claim_to_memory                                                                                               |         154 (  0.1%) |         117 (  0.0%) |          18 (  0.0%) |           0 (  0.0%) |          34 (  0.0%) |
| ······tasmlib_memory_memcpy                                                                                             |         213 (  0.1%) |         154 (  0.1%) |          58 (  0.0%) |           0 (  0.0%) |         125 (  0.2%) |
| ········tasmlib_memory_memcpy_loop_copy_5_words                                                                         |          85 (  0.0%) |          86 (  0.0%) |          50 (  0.0%) |           0 (  0.0%) |          35 (  0.0%) |
| ········tasmlib_memory_memcpy_loop_copy_single_words                                                                    |          72 (  0.0%) |          40 (  0.0%) |           8 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ··verify                                                                                                                |      291942 ( 99.9%) |      274917 ( 99.9%) |      298979 (100.0%) |       80443 ( 54.8%) |       76229 ( 99.8%) |
| ····default                                                                                                             |           5 (  0.0%) |           4 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····box_new_StarkParameters                                                                                             |          31 (  0.0%) |          31 (  0.0%) |           8 (  0.0%) |           0 (  0.0%) |          32 (  0.0%) |
| ······tasmlib_memory_dyn_malloc                                                                                         |         100 (  0.0%) |          95 (  0.0%) |          10 (  0.0%) |           0 (  0.0%) |         160 (  0.2%) |
| ····tasmlib_hashing_sponge_hasher_init                                                                                  |           2 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           1 (  0.0%) |           0 (  0.0%) |
| ····tasmlib_verifier_claim_instantiate_fiat_shamir_with_claim                                                           |         137 (  0.0%) |         105 (  0.0%) |          12 (  0.0%) |          12 (  0.0%) |          10 (  0.0%) |
| ······tasmlib_hashing_absorb_multiple                                                                                   |         126 (  0.0%) |          98 (  0.0%) |          10 (  0.0%) |          12 (  0.0%) |          10 (  0.0%) |
| ········tasmlib_hashing_absorb_multiple_absorb_all_full_chunks                                                          |          11 (  0.0%) |           8 (  0.0%) |          10 (  0.0%) |           6 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_hashing_absorb_multiple_pad_varnum_zeros                                                                |          77 (  0.0%) |          49 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_hashing_absorb_multiple_read_remainder                                                                  |           5 (  0.0%) |           4 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····new                                                                                                                 |           6 (  0.0%) |           5 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····box_new_VmProofIter                                                                                                 |          37 (  0.0%) |          32 (  0.0%) |           9 (  0.0%) |           0 (  0.0%) |          32 (  0.0%) |
| ······store_VmProofIter_to_memory                                                                                       |           7 (  0.0%) |           6 (  0.0%) |           5 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····method_boxed_LVmProofIterR_next_as_log2paddedheight                                                                 |         160 (  0.1%) |         118 (  0.0%) |           8 (  0.0%) |           6 (  0.0%) |           8 (  0.0%) |
| ······tasmlib_verifier_vm_proof_iter_dequeue_next_as_log2paddedheight                                                   |         158 (  0.1%) |         118 (  0.0%) |           8 (  0.0%) |           6 (  0.0%) |           8 (  0.0%) |
| ········tasmlib_hashing_absorb_multiple                                                                                 |        2892 (  1.0%) |        2068 (  0.8%) |        2870 (  1.0%) |        1752 (  1.2%) |          59 (  0.1%) |
| ··········tasmlib_hashing_absorb_multiple_absorb_all_full_chunks                                                        |        1742 (  0.6%) |        1168 (  0.4%) |        2820 (  0.9%) |        1692 (  1.2%) |           0 (  0.0%) |
| ··········tasmlib_hashing_absorb_multiple_pad_varnum_zeros                                                              |         370 (  0.1%) |         240 (  0.1%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ··········tasmlib_hashing_absorb_multiple_read_remainder                                                                |         450 (  0.2%) |         290 (  0.1%) |          50 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····tasmlib_arithmetic_u32_shift_left                                                                                   |          11 (  0.0%) |           9 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |          22 (  0.0%) |
| ····method_boxed_LStarkParametersR_derive_fri                                                                           |         337 (  0.1%) |         293 (  0.1%) |           4 (  0.0%) |           0 (  0.0%) |         221 (  0.3%) |
| ······method_boxed_LStarkParametersR_randomized_trace_len                                                               |         220 (  0.1%) |         166 (  0.1%) |           2 (  0.0%) |           0 (  0.0%) |          95 (  0.1%) |
| ········tasmlib_arithmetic_u32_safe_add                                                                                 |        9024 (  3.1%) |        7896 (  2.9%) |           0 (  0.0%) |           0 (  0.0%) |        4162 (  5.5%) |
| ········tasmlib_arithmetic_u32_safe_mul                                                                                 |          32 (  0.0%) |          28 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |          20 (  0.0%) |
| ········_binop_Lt__LboolR_bool_81_else                                                                                  |           2 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ········num_randomized_quotient_segments                                                                                |           4 (  0.0%) |           2 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ········_binop_Lt__LboolR_bool_91_then                                                                                  |          12 (  0.0%) |           8 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_arithmetic_u32_next_power_of_two                                                                        |          40 (  0.0%) |          28 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |          27 (  0.0%) |
| ··········tasmlib_arithmetic_u32_next_power_of_two_greater_than_one                                                     |          24 (  0.0%) |          16 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |          16 (  0.0%) |
| ······tasmlib_arithmetic_u32_safe_mul                                                                                   |           8 (  0.0%) |           7 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |          14 (  0.0%) |
| ······tasmlib_arithmetic_u32_shift_left                                                                                 |          11 (  0.0%) |           9 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |          46 (  0.1%) |
| ······tasmlib_arithmetic_bfe_primitive_root_of_unity                                                                    |         332 (  0.1%) |         330 (  0.1%) |           0 (  0.0%) |           0 (  0.0%) |          76 (  0.1%) |
| ····box_new_FriVerify                                                                                                   |          37 (  0.0%) |          32 (  0.0%) |           9 (  0.0%) |           0 (  0.0%) |          32 (  0.0%) |
| ······store_FriVerify_to_memory                                                                                         |           7 (  0.0%) |           6 (  0.0%) |           5 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····method_boxed_LStarkParametersR_trace_domain_len                                                                     |         132 (  0.0%) |          99 (  0.0%) |           1 (  0.0%) |           0 (  0.0%) |          18 (  0.0%) |
| ······tasmlib_arithmetic_u32_shift_right                                                                                |          13 (  0.0%) |          11 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |          18 (  0.0%) |
| ····method_boxed_LVmProofIterR_next_as_merkleroot                                                                       |         480 (  0.2%) |         354 (  0.1%) |          36 (  0.0%) |          18 (  0.0%) |           9 (  0.0%) |
| ······tasmlib_verifier_vm_proof_iter_dequeue_next_as_merkleroot                                                         |         474 (  0.2%) |         354 (  0.1%) |          36 (  0.0%) |          18 (  0.0%) |           9 (  0.0%) |
| ····tasmlib_verifier_challenges_new_generic_dyn_claim_59_4                                                              |        1793 (  0.6%) |        2586 (  0.9%) |         213 (  0.1%) |         108 (  0.1%) |           0 (  0.0%) |
| ······tasmlib_hashing_algebraic_hasher_sample_scalars_static_length_static_pointer_59_18446744056529682432              |         113 (  0.0%) |         398 (  0.1%) |         180 (  0.1%) |         108 (  0.1%) |           0 (  0.0%) |
| ········tasmlib_hashing_squeeze_repeatedly_static_number_18                                                             |         110 (  0.0%) |         397 (  0.1%) |         180 (  0.1%) |         108 (  0.1%) |           0 (  0.0%) |
| ······tasmlib_verifier_eval_arg_compute_terminal_dyn_sized_dynamic_symbols                                              |          52 (  0.0%) |          28 (  0.0%) |           2 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_verifier_eval_arg_compute_terminal_dyn_sized_dynamic_symbols_loop                                       |          10 (  0.0%) |           8 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ······tasmlib_verifier_eval_arg_compute_terminal_from_digest                                                            |          37 (  0.0%) |          45 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ······tasmlib_verifier_eval_arg_compute_terminal_const_sized_static_symbols_symbol_count_256_16790708486107472414       |        1537 (  0.5%) |        2048 (  0.7%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····num_quotients                                                                                                       |           2 (  0.0%) |           1 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····tasmlib_hashing_algebraic_hasher_sample_scalars                                                                     |        3787 (  1.3%) |        8016 (  2.9%) |        3302 (  1.1%) |        1974 (  1.3%) |         125 (  0.2%) |
| ······tasmlib_list_new                                                                                                  |          78 (  0.0%) |          63 (  0.0%) |           9 (  0.0%) |           0 (  0.0%) |          96 (  0.1%) |
| ········tasmlib_memory_dyn_malloc                                                                                       |          60 (  0.0%) |          57 (  0.0%) |           6 (  0.0%) |           0 (  0.0%) |          96 (  0.1%) |
| ······tasmlib_list_set_length                                                                                           |          12 (  0.0%) |           3 (  0.0%) |           3 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ······tasmlib_hashing_squeeze_repeatedly                                                                                |        3634 (  1.2%) |        7908 (  2.9%) |        3290 (  1.1%) |        1974 (  1.3%) |           0 (  0.0%) |
| ····method_Result___array611_of_LXFieldR_unwrap                                                                         |           2 (  0.0%) |           1 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····generator_for_length                                                                                                |         252 (  0.1%) |         225 (  0.1%) |           0 (  0.0%) |           0 (  0.0%) |          66 (  0.1%) |
| ······is_power_of_two                                                                                                   |          61 (  0.0%) |          41 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |          23 (  0.0%) |
| ········tasmlib_arithmetic_u64_sub                                                                                      |          20 (  0.0%) |          14 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |          11 (  0.0%) |
| ········tasmlib_arithmetic_u64_and                                                                                      |           6 (  0.0%) |           2 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |          12 (  0.0%) |
| ····zeta                                                                                                                |           2 (  0.0%) |           1 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····method_boxed_LVmProofIterR_next_as_outofdomainmainrow                                                               |        1676 (  0.6%) |        1140 (  0.4%) |        2288 (  0.8%) |        1368 (  0.9%) |          17 (  0.0%) |
| ······tasmlib_verifier_vm_proof_iter_dequeue_next_as_outofdomainmainrow                                                 |        1672 (  0.6%) |        1140 (  0.4%) |        2288 (  0.8%) |        1368 (  0.9%) |          17 (  0.0%) |
| ····method_boxed_LVmProofIterR_next_as_outofdomainauxrow                                                                |         644 (  0.2%) |         452 (  0.2%) |         560 (  0.2%) |         336 (  0.2%) |          15 (  0.0%) |
| ······tasmlib_verifier_vm_proof_iter_dequeue_next_as_outofdomainauxrow                                                  |         640 (  0.2%) |         452 (  0.2%) |         560 (  0.2%) |         336 (  0.2%) |          15 (  0.0%) |
| ····method_boxed_LVmProofIterR_next_as_outofdomainquotientsegments                                                      |         332 (  0.1%) |         244 (  0.1%) |          38 (  0.0%) |          24 (  0.0%) |          10 (  0.0%) |
| ······tasmlib_verifier_vm_proof_iter_dequeue_next_as_outofdomainquotientsegments                                        |         328 (  0.1%) |         244 (  0.1%) |          38 (  0.0%) |          24 (  0.0%) |          10 (  0.0%) |
| ····tasmlib_verifier_master_table_air_constraint_evaluation                                                             |       45772 ( 15.7%) |       70709 ( 25.7%) |       29012 (  9.7%) |           0 (  0.0%) |           0 (  0.0%) |
| ····tasmlib_verifier_master_table_divide_out_zerofiers                                                                  |        7497 (  2.6%) |        8699 (  3.2%) |        5514 (  1.8%) |           0 (  0.0%) |          11 (  0.0%) |
| ······tasmlib_verifier_master_table_zerofiers_inverse                                                                   |         157 (  0.1%) |         139 (  0.1%) |          15 (  0.0%) |           0 (  0.0%) |          11 (  0.0%) |
| ········tasmlib_arithmetic_xfe_to_the_power_of_power_of_2                                                               |         117 (  0.0%) |          95 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ··········tasmlib_arithmetic_xfe_to_the_power_of_power_of_2_loop                                                        |         113 (  0.0%) |          94 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····tasmlib_array_inner_product_of_611_xfes                                                                             |         618 (  0.2%) |           5 (  0.0%) |        3666 (  1.2%) |           0 (  0.0%) |           0 (  0.0%) |
| ····tasmlib_array_horner_evaluation_with_4_coefficients                                                                 |          86 (  0.0%) |         110 (  0.0%) |          24 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····num_main_aux_quotient_deep_weights                                                                                  |           2 (  0.0%) |           1 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····num_columns_plus_quotient_segments                                                                                  |           2 (  0.0%) |           1 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····tasmlib_list_split_off_xfe                                                                                          |         241 (  0.1%) |         192 (  0.1%) |          64 (  0.0%) |           0 (  0.0%) |         175 (  0.2%) |
| ····method_Result___array4_of_LXFieldR_unwrap                                                                           |           2 (  0.0%) |           1 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····num_columns                                                                                                         |           2 (  0.0%) |           1 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····method_Result___array5_of_LXFieldR_unwrap                                                                           |           2 (  0.0%) |           1 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····linearly_sum_xfe_main_and_aux_row                                                                                   |       62418 ( 21.4%) |       62032 ( 22.5%) |        5640 (  1.9%) |           0 (  0.0%) |       35647 ( 46.7%) |
| ······_binop_Lt__LboolR_bool_279_while_loop                                                                             |       48532 ( 16.6%) |       48528 ( 17.6%) |        4548 (  1.5%) |           0 (  0.0%) |       31099 ( 40.7%) |
| ······_binop_Lt__LboolR_bool_298_while_loop                                                                             |       13852 (  4.7%) |       13484 (  4.9%) |        1092 (  0.4%) |           0 (  0.0%) |        4548 (  6.0%) |
| ····tasmlib_array_inner_product_of_4_xfes                                                                               |          22 (  0.0%) |          10 (  0.0%) |          48 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····method_boxed_LFriVerifyR_verify                                                                                     |       57188 ( 19.6%) |       49287 ( 17.9%) |       20327 (  6.8%) |       24996 ( 17.0%) |       33064 ( 43.3%) |
| ······tasmlib_verifier_fri_verify                                                                                       |       57181 ( 19.6%) |       49283 ( 17.9%) |       20327 (  6.8%) |       24996 ( 17.0%) |       33064 ( 43.3%) |
| ········tasmlib_verifier_fri_number_of_rounds                                                                           |          32 (  0.0%) |          22 (  0.0%) |           3 (  0.0%) |           0 (  0.0%) |          43 (  0.1%) |
| ········tasmlib_list_new                                                                                                |          78 (  0.0%) |          63 (  0.0%) |           9 (  0.0%) |           0 (  0.0%) |          96 (  0.1%) |
| ··········tasmlib_memory_dyn_malloc                                                                                     |         100 (  0.0%) |          95 (  0.0%) |          10 (  0.0%) |           0 (  0.0%) |         160 (  0.2%) |
| ········tasmlib_verifier_vm_proof_iter_dequeue_next_as_merkleroot                                                       |         158 (  0.1%) |         118 (  0.0%) |          12 (  0.0%) |           6 (  0.0%) |           0 (  0.0%) |
| ··········tasmlib_hashing_absorb_multiple                                                                               |         120 (  0.0%) |          94 (  0.0%) |           6 (  0.0%) |           6 (  0.0%) |           0 (  0.0%) |
| ············tasmlib_hashing_absorb_multiple_absorb_all_full_chunks                                                      |           5 (  0.0%) |           4 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ············tasmlib_hashing_absorb_multiple_pad_varnum_zeros                                                            |          29 (  0.0%) |          19 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ············tasmlib_hashing_absorb_multiple_read_remainder                                                              |          53 (  0.0%) |          34 (  0.0%) |           6 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_list_push___digest                                                                                      |          21 (  0.0%) |          18 (  0.0%) |           7 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_verifier_fri_verify_dequeue_commit_phase_remainder                                                      |         779 (  0.3%) |         646 (  0.2%) |         132 (  0.0%) |          36 (  0.0%) |          96 (  0.1%) |
| ··········tasmlib_hashing_algebraic_hasher_sample_scalars_static_length_dyn_malloc_1                                    |          96 (  0.0%) |         129 (  0.0%) |          36 (  0.0%) |          18 (  0.0%) |          96 (  0.1%) |
| ············tasmlib_memory_dyn_malloc                                                                                   |         180 (  0.1%) |         171 (  0.1%) |          18 (  0.0%) |           0 (  0.0%) |         288 (  0.4%) |
| ············tasmlib_hashing_squeeze_repeatedly_static_number_1                                                          |          24 (  0.0%) |          69 (  0.0%) |          30 (  0.0%) |          18 (  0.0%) |           0 (  0.0%) |
| ··········tasmlib_list_push___xfe                                                                                       |          63 (  0.0%) |          48 (  0.0%) |          15 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ··········tasmlib_verifier_vm_proof_iter_dequeue_next_as_merkleroot                                                     |         474 (  0.2%) |         354 (  0.1%) |          36 (  0.0%) |          18 (  0.0%) |           0 (  0.0%) |
| ············tasmlib_hashing_absorb_multiple                                                                             |         708 (  0.2%) |         528 (  0.2%) |         406 (  0.1%) |         252 (  0.2%) |          10 (  0.0%) |
| ··············tasmlib_hashing_absorb_multiple_absorb_all_full_chunks                                                    |         248 (  0.1%) |         168 (  0.1%) |         380 (  0.1%) |         228 (  0.2%) |           0 (  0.0%) |
| ··············tasmlib_hashing_absorb_multiple_pad_varnum_zeros                                                          |         100 (  0.0%) |          66 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ··············tasmlib_hashing_absorb_multiple_read_remainder                                                            |         228 (  0.1%) |         146 (  0.1%) |          26 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ··········tasmlib_list_push___digest                                                                                    |          63 (  0.0%) |          54 (  0.0%) |          21 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_verifier_vm_proof_iter_dequeue_next_as_fricodeword                                                      |          58 (  0.0%) |          42 (  0.0%) |           9 (  0.0%) |           0 (  0.0%) |          54 (  0.1%) |
| ········tasmlib_list_length                                                                                             |          15 (  0.0%) |          10 (  0.0%) |           5 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_hashing_merkle_root_from_xfes                                                                           |        6449 (  2.2%) |       10492 (  3.8%) |        6653 (  2.2%) |        3066 (  2.1%) |          99 (  0.1%) |
| ··········tasmlib_hashing_merkle_root_from_xfes_build_1st_layer                                                         |        3840 (  1.3%) |        5120 (  1.9%) |        2816 (  0.9%) |        1536 (  1.0%) |           0 (  0.0%) |
| ··········tasmlib_hashing_merkle_root                                                                                   |        2544 (  0.9%) |        5320 (  1.9%) |        3833 (  1.3%) |        1530 (  1.0%) |          42 (  0.1%) |
| ············tasmlib_hashing_merkle_root_next_layer_loop                                                                 |        2500 (  0.9%) |        5280 (  1.9%) |        3825 (  1.3%) |        1530 (  1.0%) |           0 (  0.0%) |
| ··············tasmlib_hashing_merkle_root_calculate_parent_digests                                                      |        2295 (  0.8%) |        5100 (  1.9%) |        3825 (  1.3%) |        1530 (  1.0%) |           0 (  0.0%) |
| ········tasmlib_list_get_element___digest                                                                               |          40 (  0.0%) |          38 (  0.0%) |          12 (  0.0%) |           0 (  0.0%) |           4 (  0.0%) |
| ··········tasmlib_list_length                                                                                           |           9 (  0.0%) |           6 (  0.0%) |           3 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_verifier_vm_proof_iter_dequeue_next_as_fripolynomial                                                    |         451 (  0.2%) |         326 (  0.1%) |         403 (  0.1%) |         234 (  0.2%) |          94 (  0.1%) |
| ··········tasmlib_hashing_sponge_hasher_pad_and_absorb_all                                                              |         353 (  0.1%) |         247 (  0.1%) |         389 (  0.1%) |         234 (  0.2%) |          10 (  0.0%) |
| ········tasmlib_hashing_algebraic_hasher_sample_indices                                                                 |        4636 (  1.6%) |        3167 (  1.2%) |         332 (  0.1%) |          48 (  0.0%) |        5214 (  6.8%) |
| ··········tasmlib_list_new                                                                                              |         130 (  0.0%) |         105 (  0.0%) |          15 (  0.0%) |           0 (  0.0%) |         160 (  0.2%) |
| ··········tasmlib_hashing_algebraic_hasher_sample_indices_main_loop                                                     |        4601 (  1.6%) |        3142 (  1.1%) |         329 (  0.1%) |          48 (  0.0%) |        5182 (  6.8%) |
| ············tasmlib_list_length                                                                                         |         285 (  0.1%) |         190 (  0.1%) |          95 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ············tasmlib_hashing_algebraic_hasher_sample_indices_then_reduce_and_save                                        |        2720 (  0.9%) |        1520 (  0.6%) |         240 (  0.1%) |           0 (  0.0%) |        5182 (  6.8%) |
| ··············tasmlib_list_push___u32                                                                                   |        1440 (  0.5%) |         960 (  0.3%) |         240 (  0.1%) |           0 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_hashing_algebraic_hasher_sample_scalars_static_length_dyn_malloc_1                                      |          32 (  0.0%) |          43 (  0.0%) |          12 (  0.0%) |           6 (  0.0%) |          32 (  0.0%) |
| ··········tasmlib_hashing_squeeze_repeatedly_static_number_1                                                            |           8 (  0.0%) |          23 (  0.0%) |          10 (  0.0%) |           6 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_list_horner_evaluation_dynamic_length                                                                   |        1384 (  0.5%) |        1995 (  0.7%) |         385 (  0.1%) |           0 (  0.0%) |          33 (  0.0%) |
| ··········tasmlib_list_horner_evaluation_dynamic_length_loop_batches                                                    |        1096 (  0.4%) |        1648 (  0.6%) |         336 (  0.1%) |           0 (  0.0%) |          33 (  0.0%) |
| ··········tasmlib_list_horner_evaluation_dynamic_length_loop_remainder                                                  |         263 (  0.1%) |         326 (  0.1%) |          48 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_verifier_fri_barycentric_evaluation                                                                     |       11996 (  4.1%) |        9425 (  3.4%) |        6145 (  2.1%) |           0 (  0.0%) |          17 (  0.0%) |
| ··········tasmlib_arithmetic_bfe_primitive_root_of_unity                                                                |         166 (  0.1%) |         165 (  0.1%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ··········tasmlib_verifier_fri_barycentric_evaluation_partial_terms_loop                                                |        7168 (  2.5%) |        6144 (  2.2%) |        1536 (  0.5%) |           0 (  0.0%) |           0 (  0.0%) |
| ··········tasmlib_verifier_fri_barycentric_evaluation_numerator_from_partial_sums                                       |        2048 (  0.7%) |           0 (  0.0%) |        3072 (  1.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ··········tasmlib_verifier_fri_barycentric_evaluation_denominator_from_partial_sums                                     |        2560 (  0.9%) |        3072 (  1.1%) |        1536 (  0.5%) |           0 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_verifier_vm_proof_iter_dequeue_next_as_friresponse                                                      |          96 (  0.0%) |          72 (  0.0%) |          12 (  0.0%) |           0 (  0.0%) |         144 (  0.2%) |
| ········tasmlib_verifier_fri_verify_fri_authentication_paths                                                            |        3444 (  1.2%) |        1450 (  0.5%) |         320 (  0.1%) |        5760 (  3.9%) |        7905 ( 10.4%) |
| ··········tasmlib_verifier_fri_verify_fri_authentication_paths_main_loop                                                |        3440 (  1.2%) |        1440 (  0.5%) |         320 (  0.1%) |        5760 (  3.9%) |        7905 ( 10.4%) |
| ············tasmlib_verifier_fri_verify_fri_authentication_paths_loop_over_auth_path_elements                           |        1920 (  0.7%) |           0 (  0.0%) |           0 (  0.0%) |        5760 (  3.9%) |        5772 (  7.6%) |
| ········tasmlib_list_higher_order_u32_zip_u32_with_xfe                                                                  |        3170 (  1.1%) |        3306 (  1.2%) |        1292 (  0.4%) |           0 (  0.0%) |          64 (  0.1%) |
| ··········tasmlib_list_higher_order_u32_zip_u32_with_xfe_loop                                                           |        3050 (  1.0%) |        3208 (  1.2%) |        1280 (  0.4%) |           0 (  0.0%) |           0 (  0.0%) |
| ········tasmlib_verifier_fri_verify_query_phase_main_loop                                                               |       19613 (  6.7%) |       13948 (  5.1%) |        3429 (  1.1%) |       15840 ( 10.8%) |       16820 ( 22.0%) |
| ··········tasmlib_verifier_vm_proof_iter_dequeue_next_as_friresponse                                                    |         288 (  0.1%) |         216 (  0.1%) |          36 (  0.0%) |           0 (  0.0%) |         168 (  0.2%) |
| ··········tasmlib_list_get_element___digest                                                                             |          60 (  0.0%) |          57 (  0.0%) |          18 (  0.0%) |           0 (  0.0%) |           8 (  0.0%) |
| ··········tasmlib_verifier_fri_verify_fri_authentication_paths                                                          |        9852 (  3.4%) |        4350 (  1.6%) |         960 (  0.3%) |       15840 ( 10.8%) |       13764 ( 18.0%) |
| ············tasmlib_verifier_fri_verify_fri_authentication_paths_main_loop                                              |        9840 (  3.4%) |        4320 (  1.6%) |         960 (  0.3%) |       15840 ( 10.8%) |       13764 ( 18.0%) |
| ··············tasmlib_verifier_fri_verify_fri_authentication_paths_loop_over_auth_path_elements                         |        5280 (  1.8%) |           0 (  0.0%) |           0 (  0.0%) |       15840 ( 10.8%) |        8766 ( 11.5%) |
| ··········tasmlib_list_get_element___xfe                                                                                |          60 (  0.0%) |          51 (  0.0%) |          12 (  0.0%) |           0 (  0.0%) |           9 (  0.0%) |
| ··········tasmlib_verifier_fri_verify_compute_c_values_loop                                                             |        9120 (  3.1%) |        9120 (  3.3%) |        2400 (  0.8%) |           0 (  0.0%) |        2853 (  3.7%) |
| ········tasmlib_list_higher_order_u32_map_tasmlib_verifier_fri_verify_reduce_indices                                    |        1338 (  0.5%) |         678 (  0.2%) |         166 (  0.1%) |           0 (  0.0%) |        1724 (  2.3%) |
| ··········tasmlib_list_higher_order_u32_map_tasmlib_verifier_fri_verify_reduce_indices_loop                             |        1285 (  0.4%) |         644 (  0.2%) |         160 (  0.1%) |           0 (  0.0%) |        1692 (  2.2%) |
| ········tasmlib_list_higher_order_u32_map_tasmlib_verifier_fri_verify_assert_codeword_membership                        |        3183 (  1.1%) |        3242 (  1.2%) |         966 (  0.3%) |           0 (  0.0%) |         568 (  0.7%) |
| ··········tasmlib_list_higher_order_u32_map_tasmlib_verifier_fri_verify_assert_codeword_membership_loop                 |        3125 (  1.1%) |        3204 (  1.2%) |         960 (  0.3%) |           0 (  0.0%) |         536 (  0.7%) |
| ············tasmlib_list_get_element___xfe                                                                              |        1600 (  0.5%) |        1360 (  0.5%) |         320 (  0.1%) |           0 (  0.0%) |         536 (  0.7%) |
| ··············tasmlib_list_length                                                                                       |         240 (  0.1%) |         160 (  0.1%) |          80 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····method_boxed_LVmProofIterR_next_as_mastermaintablerows                                                              |          60 (  0.0%) |          42 (  0.0%) |           9 (  0.0%) |           0 (  0.0%) |          24 (  0.0%) |
| ······tasmlib_verifier_vm_proof_iter_dequeue_next_as_mastermaintablerows                                                |          58 (  0.0%) |          42 (  0.0%) |           9 (  0.0%) |           0 (  0.0%) |          24 (  0.0%) |
| ····method_boxed_LVmProofIterR_next_as_authenticationstructure                                                          |         180 (  0.1%) |         126 (  0.0%) |          27 (  0.0%) |           0 (  0.0%) |          24 (  0.0%) |
| ······tasmlib_verifier_vm_proof_iter_dequeue_next_as_authenticationstructure                                            |         174 (  0.1%) |         126 (  0.0%) |          27 (  0.0%) |           0 (  0.0%) |          24 (  0.0%) |
| ····tasmlib_verifier_master_table_verify_Main_table_rows                                                                |       10029 (  3.4%) |        5793 (  2.1%) |       30406 ( 10.2%) |       24560 ( 16.7%) |           5 (  0.0%) |
| ······tasmlib_verifier_master_table_verify_Main_table_rows_loop_over_rows                                               |       10005 (  3.4%) |        5764 (  2.1%) |       30400 ( 10.2%) |       24560 ( 16.7%) |           0 (  0.0%) |
| ········tasmlib_hashing_algebraic_hasher_hash_static_size_379                                                           |        5600 (  1.9%) |        3920 (  1.4%) |       30320 ( 10.1%) |       18800 ( 12.8%) |           0 (  0.0%) |
| ··········tasmlib_hashing_absorb_multiple_static_size_379                                                               |        4400 (  1.5%) |        2720 (  1.0%) |       30320 ( 10.1%) |       18240 ( 12.4%) |           0 (  0.0%) |
| ········tasmlib_verifier_master_table_verify_Main_table_rows_loop_over_auth_path_elements                               |        1920 (  0.7%) |           0 (  0.0%) |           0 (  0.0%) |        5760 (  3.9%) |           0 (  0.0%) |
| ····method_boxed_LVmProofIterR_next_as_masterauxtablerows                                                               |          60 (  0.0%) |          42 (  0.0%) |           9 (  0.0%) |           0 (  0.0%) |          24 (  0.0%) |
| ······tasmlib_verifier_vm_proof_iter_dequeue_next_as_masterauxtablerows                                                 |          58 (  0.0%) |          42 (  0.0%) |           9 (  0.0%) |           0 (  0.0%) |          24 (  0.0%) |
| ····tasmlib_verifier_master_table_verify_Aux_table_rows                                                                 |        9629 (  3.3%) |        5793 (  2.1%) |       21926 (  7.3%) |       19760 ( 13.5%) |           0 (  0.0%) |
| ······tasmlib_verifier_master_table_verify_Aux_table_rows_loop_over_rows                                                |        9605 (  3.3%) |        5764 (  2.1%) |       21920 (  7.3%) |       19760 ( 13.5%) |           0 (  0.0%) |
| ········tasmlib_hashing_algebraic_hasher_hash_static_size_273                                                           |        5200 (  1.8%) |        3920 (  1.4%) |       21840 (  7.3%) |       14000 (  9.5%) |           0 (  0.0%) |
| ··········tasmlib_hashing_absorb_multiple_static_size_273                                                               |        4000 (  1.4%) |        2720 (  1.0%) |       21840 (  7.3%) |       13440 (  9.2%) |           0 (  0.0%) |
| ········tasmlib_verifier_master_table_verify_Aux_table_rows_loop_over_auth_path_elements                                |        1920 (  0.7%) |           0 (  0.0%) |           0 (  0.0%) |        5760 (  3.9%) |           0 (  0.0%) |
| ····method_boxed_LVmProofIterR_next_as_quotientsegmentselements                                                         |          60 (  0.0%) |          42 (  0.0%) |           9 (  0.0%) |           0 (  0.0%) |          24 (  0.0%) |
| ······tasmlib_verifier_vm_proof_iter_dequeue_next_as_quotientsegmentselements                                           |          58 (  0.0%) |          42 (  0.0%) |           9 (  0.0%) |           0 (  0.0%) |          24 (  0.0%) |
| ····tasmlib_verifier_master_table_verify_Quotient_table_rows                                                            |        7389 (  2.5%) |        5793 (  2.1%) |        1286 (  0.4%) |        7280 (  5.0%) |           0 (  0.0%) |
| ······tasmlib_verifier_master_table_verify_Quotient_table_rows_loop_over_rows                                           |        7365 (  2.5%) |        5764 (  2.1%) |        1280 (  0.4%) |        7280 (  5.0%) |           0 (  0.0%) |
| ········tasmlib_hashing_algebraic_hasher_hash_static_size_15                                                            |        2960 (  1.0%) |        3920 (  1.4%) |        1200 (  0.4%) |        1520 (  1.0%) |           0 (  0.0%) |
| ··········tasmlib_hashing_absorb_multiple_static_size_15                                                                |        1760 (  0.6%) |        2720 (  1.0%) |        1200 (  0.4%) |         960 (  0.7%) |           0 (  0.0%) |
| ········tasmlib_verifier_master_table_verify_Quotient_table_rows_loop_over_auth_path_elements                           |        1920 (  0.7%) |           0 (  0.0%) |           0 (  0.0%) |        5760 (  3.9%) |           0 (  0.0%) |
| ····method_Result___array470_of_LXFieldR_unwrap                                                                         |           2 (  0.0%) |           1 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| ····_binop_Lt__LboolR_bool_403_while_loop                                                                               |       80090 ( 27.4%) |       51688 ( 18.8%) |      174321 ( 58.3%) |           0 (  0.0%) |        6344 (  8.3%) |
| ······tasmlib_array_inner_product_of_three_rows_with_weights_Bfe_mainrowelem                                            |       38320 ( 13.1%) |         480 (  0.2%) |      164960 ( 55.2%) |           0 (  0.0%) |           0 (  0.0%) |
| ······tasmlib_arithmetic_u32_safe_add                                                                                   |         640 (  0.2%) |         560 (  0.2%) |           0 (  0.0%) |           0 (  0.0%) |           0 (  0.0%) |
| Total                                                                                                                   |      292233 (100.0%) |      275146 (100.0%) |      299007 (100.0%) |      146737 (100.0%) |       76360 (100.0%) |

| Table     | Height | Dominates |
|:----------|-------:|----------:|
| Program   | 110490 |        no |
| Processor | 292233 |        no |
| OpStack   | 275146 |        no |
| Ram       | 299007 |       yes |
| JumpStack | 292233 |        no |
| Hash      | 146737 |        no |
| Cascade   |  65536 |        no |
| Lookup    |    256 |        no |
| U32       |  76360 |        no |

Padded height: 2^19
